require('plugins')
require('custom-keys')
require('file-explorer')
require('file-finder')
require('gopls')
require('mason-config')
require('styling')
require('statusbar')
require('syntax-highlight')

vim.cmd('set nocompatible')
vim.cmd('set number')
vim.cmd('set relativenumber')
vim.cmd('set rnu')
vim.cmd('filetype plugin indent on')
vim.cmd('set cursorline')
